config/routes.rb
Rails.application.routes.draw do
  resources :concerts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "concerts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/concert.rb
class Concert < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  before_action :set_concert, only: %i[ show edit update destroy ]

  # GET /concerts or /concerts.json
  def index
    @concerts = Concert.all
  end

  # GET /concerts/1 or /concerts/1.json
  def show
  end

  # GET /concerts/new
  def new
    @concert = Concert.new
  end

  # GET /concerts/1/edit
  def edit
  end

  # POST /concerts or /concerts.json
  def create
    @concert = Concert.new(concert_params)

    respond_to do |format|
      if @concert.save
        format.html { redirect_to concert_url(@concert), notice: "Concert was successfully created." }
        format.json { render :show, status: :created, location: @concert }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concerts/1 or /concerts/1.json
  def update
    respond_to do |format|
      if @concert.update(concert_params)
        format.html { redirect_to concert_url(@concert), notice: "Concert was successfully updated." }
        format.json { render :show, status: :ok, location: @concert }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concerts/1 or /concerts/1.json
  def destroy
    @concert.destroy!

    respond_to do |format|
      format.html { redirect_to concerts_url, notice: "Concert was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concert
      @concert = Concert.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concert_params
      params.require(:concert).permit(:event_name, :time, :repeat)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/views/concerts/_concert.html.erb
<tr id="<%= dom_id concert %>">
  <td><%= concert.event_name %></td>
  <td><%= concert.time %></td>
  <td><%= concert.repeat %></td>
  <td>
    <p>
      <%= link_to "Show this concert", concert %>
    </p>
  </td>
</tr>

app/views/concerts/_form.html.erb
<%= form_with(model: concert) do |form| %>
  <% if concert.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(concert.errors.count, "error") %> prohibited this concert from being saved:</h2>

      <ul>
        <% concert.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :event_name, style: "display: block" %>
    <%= form.text_field :event_name %>
  </div>

  <div>
    <%= form.label :time, style: "display: block" %>
    <%= form.datetime_field :time %>
  </div>

  <div>
    <%= form.label :repeat, style: "display: block" %>
    <%= form.check_box :repeat %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/concerts/edit.html.erb
<h1>Editing concert</h1>

<%= render "form", concert: @concert %>

<br>

<div>
  <%= link_to "Show this concert", @concert %> |
  <%= link_to "Back to concerts", concerts_path %>
</div>

app/views/concerts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="text-3xl font-bold underline">Concerts</h1>

<div class="flex flex-col justify-center items-center">
  <div>
    <table class="table-auto border-2 border-amber-500">
      <thead>
      <tr>
        <th>Event Name</th>
        <th>Time</th>
        <th>Repeat</th>
      </tr>
      </thead>
      <tbody>
          <% @concerts.each do |concert| %>
            <%= render concert %>
          <% end %>
      </tbody>
    </table>
  </div>
  <div>
    <%= link_to "New concert", new_concert_path, class: "" %>
  </div>
</div>

app/views/concerts/new.html.erb
<h1>New concert</h1>

<%= render "form", concert: @concert %>

<br>

<div>
  <%= link_to "Back to concerts", concerts_path %>
</div>

app/views/concerts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @concert %>

<div>
  <%= link_to "Edit this concert", edit_concert_path(@concert) %> |
  <%= link_to "Back to concerts", concerts_path %>

  <%= button_to "Destroy this concert", @concert, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireRailsStim</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container mx-auto">
    <%= yield %>
  </div>
  </body>
</html>